Update sca.yml

diff --git a/.github/workflows/sca.yml b/.github/workflows/sca.yml
--- a/.github/workflows/sca.yml
+++ b/.github/workflows/sca.yml
@@ -1,11 +1,11 @@
-name: SAST Check
+name: SCA Check
 on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
 jobs:
-  sast-check:
+  sca-check:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
@@ -22,25 +22,25 @@ jobs:
       - name: Create project zip
         run: zip -r project.zip . -x "*.git*" "*/node_modules/*" "*/vendor/*" "*.zip"
       
-      - name: Perform SAST Scan
-        id: sast
+      - name: Perform SCA Scan
+        id: sca
         run: |
           RESPONSE=$(curl -X POST \
             -H "Client-ID: ${{ secrets.INTRUCEPT_CLIENT_ID }}" \
             -H "Client-Secret: ${{ secrets.INTRUCEPT_CLIENT_SECRET }}" \
             -F "projectZipFile=@project.zip" \
             -F "applicationId=${{ secrets.INTRUCEPT_APPLICATION_ID }}" \
-            -F "scanName=Golang SAST Scan - ${{ github.sha }}" \
-            -F "language=kotlin" \
-            https://appsecops-api.intruceptlabs.com/api/v1/integrations/sast-scans)
+            -F "scanName=Golang SCA Scan - ${{ github.sha }}" \
+            -F "language=Kotlin" \
+            https://appsecops-api.intruceptlabs.com/api/v1/integrations/sca-scans)          
           
-          # Check for error in response.
-          ERROR=$(echo "$RESPONSE" | jq -r '.error // empty')
-          if [ ! -z "$ERROR" ]; then
-             echo "Error: $ERROR"
-             exit 1
-          else
-             VULNS_TABLE=$(echo "$RESPONSE" | jq -r '.vulnsTable')
-             echo "Vulnerabilities Table:"
-             echo "$VULNS_TABLE"
-          fi 
+            # Check for error in response
+            ERROR=$(echo "$RESPONSE" | jq -r '.error // empty')
+            if [ ! -z "$ERROR" ]; then
+              echo "Error: $ERROR"
+              exit 1
+            else
+              VULNS_TABLE=$(echo "$RESPONSE" | jq -r '.vulnsTable')
+              echo "Vulnerabilities Table:"
+              echo "$VULNS_TABLE"
+            fi
